from agrimind.core.base_models import PathogenInfo
from agrimind.core.domain_types import PathogenType

EXPANDED_DISEASE_DATA_PART_16 = {
    "disease_vector_16_001": PathogenInfo(
        pathogen_id="disease_vector_16_001",
        common_name="Pathogen Condition Variant 16-1",
        scientific_name="Pathogen strain 16.1",
        pathogen_type=PathogenType.FUNGAL if 1%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_002": PathogenInfo(
        pathogen_id="disease_vector_16_002",
        common_name="Pathogen Condition Variant 16-2",
        scientific_name="Pathogen strain 16.2",
        pathogen_type=PathogenType.FUNGAL if 2%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_003": PathogenInfo(
        pathogen_id="disease_vector_16_003",
        common_name="Pathogen Condition Variant 16-3",
        scientific_name="Pathogen strain 16.3",
        pathogen_type=PathogenType.FUNGAL if 3%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_004": PathogenInfo(
        pathogen_id="disease_vector_16_004",
        common_name="Pathogen Condition Variant 16-4",
        scientific_name="Pathogen strain 16.4",
        pathogen_type=PathogenType.FUNGAL if 4%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_005": PathogenInfo(
        pathogen_id="disease_vector_16_005",
        common_name="Pathogen Condition Variant 16-5",
        scientific_name="Pathogen strain 16.5",
        pathogen_type=PathogenType.FUNGAL if 5%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_006": PathogenInfo(
        pathogen_id="disease_vector_16_006",
        common_name="Pathogen Condition Variant 16-6",
        scientific_name="Pathogen strain 16.6",
        pathogen_type=PathogenType.FUNGAL if 6%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_007": PathogenInfo(
        pathogen_id="disease_vector_16_007",
        common_name="Pathogen Condition Variant 16-7",
        scientific_name="Pathogen strain 16.7",
        pathogen_type=PathogenType.FUNGAL if 7%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_008": PathogenInfo(
        pathogen_id="disease_vector_16_008",
        common_name="Pathogen Condition Variant 16-8",
        scientific_name="Pathogen strain 16.8",
        pathogen_type=PathogenType.FUNGAL if 8%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_009": PathogenInfo(
        pathogen_id="disease_vector_16_009",
        common_name="Pathogen Condition Variant 16-9",
        scientific_name="Pathogen strain 16.9",
        pathogen_type=PathogenType.FUNGAL if 9%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_010": PathogenInfo(
        pathogen_id="disease_vector_16_010",
        common_name="Pathogen Condition Variant 16-10",
        scientific_name="Pathogen strain 16.10",
        pathogen_type=PathogenType.FUNGAL if 10%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_011": PathogenInfo(
        pathogen_id="disease_vector_16_011",
        common_name="Pathogen Condition Variant 16-11",
        scientific_name="Pathogen strain 16.11",
        pathogen_type=PathogenType.FUNGAL if 11%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_012": PathogenInfo(
        pathogen_id="disease_vector_16_012",
        common_name="Pathogen Condition Variant 16-12",
        scientific_name="Pathogen strain 16.12",
        pathogen_type=PathogenType.FUNGAL if 12%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_013": PathogenInfo(
        pathogen_id="disease_vector_16_013",
        common_name="Pathogen Condition Variant 16-13",
        scientific_name="Pathogen strain 16.13",
        pathogen_type=PathogenType.FUNGAL if 13%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_014": PathogenInfo(
        pathogen_id="disease_vector_16_014",
        common_name="Pathogen Condition Variant 16-14",
        scientific_name="Pathogen strain 16.14",
        pathogen_type=PathogenType.FUNGAL if 14%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_015": PathogenInfo(
        pathogen_id="disease_vector_16_015",
        common_name="Pathogen Condition Variant 16-15",
        scientific_name="Pathogen strain 16.15",
        pathogen_type=PathogenType.FUNGAL if 15%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_016": PathogenInfo(
        pathogen_id="disease_vector_16_016",
        common_name="Pathogen Condition Variant 16-16",
        scientific_name="Pathogen strain 16.16",
        pathogen_type=PathogenType.FUNGAL if 16%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_017": PathogenInfo(
        pathogen_id="disease_vector_16_017",
        common_name="Pathogen Condition Variant 16-17",
        scientific_name="Pathogen strain 16.17",
        pathogen_type=PathogenType.FUNGAL if 17%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_018": PathogenInfo(
        pathogen_id="disease_vector_16_018",
        common_name="Pathogen Condition Variant 16-18",
        scientific_name="Pathogen strain 16.18",
        pathogen_type=PathogenType.FUNGAL if 18%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_019": PathogenInfo(
        pathogen_id="disease_vector_16_019",
        common_name="Pathogen Condition Variant 16-19",
        scientific_name="Pathogen strain 16.19",
        pathogen_type=PathogenType.FUNGAL if 19%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_020": PathogenInfo(
        pathogen_id="disease_vector_16_020",
        common_name="Pathogen Condition Variant 16-20",
        scientific_name="Pathogen strain 16.20",
        pathogen_type=PathogenType.FUNGAL if 20%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_021": PathogenInfo(
        pathogen_id="disease_vector_16_021",
        common_name="Pathogen Condition Variant 16-21",
        scientific_name="Pathogen strain 16.21",
        pathogen_type=PathogenType.FUNGAL if 21%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_022": PathogenInfo(
        pathogen_id="disease_vector_16_022",
        common_name="Pathogen Condition Variant 16-22",
        scientific_name="Pathogen strain 16.22",
        pathogen_type=PathogenType.FUNGAL if 22%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_023": PathogenInfo(
        pathogen_id="disease_vector_16_023",
        common_name="Pathogen Condition Variant 16-23",
        scientific_name="Pathogen strain 16.23",
        pathogen_type=PathogenType.FUNGAL if 23%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_16_024": PathogenInfo(
        pathogen_id="disease_vector_16_024",
        common_name="Pathogen Condition Variant 16-24",
        scientific_name="Pathogen strain 16.24",
        pathogen_type=PathogenType.FUNGAL if 24%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
}
