from agrimind.core.base_models import PathogenInfo
from agrimind.core.domain_types import PathogenType

EXPANDED_DISEASE_DATA_PART_34 = {
    "disease_vector_34_001": PathogenInfo(
        pathogen_id="disease_vector_34_001",
        common_name="Pathogen Condition Variant 34-1",
        scientific_name="Pathogen strain 34.1",
        pathogen_type=PathogenType.FUNGAL if 1%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_002": PathogenInfo(
        pathogen_id="disease_vector_34_002",
        common_name="Pathogen Condition Variant 34-2",
        scientific_name="Pathogen strain 34.2",
        pathogen_type=PathogenType.FUNGAL if 2%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_003": PathogenInfo(
        pathogen_id="disease_vector_34_003",
        common_name="Pathogen Condition Variant 34-3",
        scientific_name="Pathogen strain 34.3",
        pathogen_type=PathogenType.FUNGAL if 3%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_004": PathogenInfo(
        pathogen_id="disease_vector_34_004",
        common_name="Pathogen Condition Variant 34-4",
        scientific_name="Pathogen strain 34.4",
        pathogen_type=PathogenType.FUNGAL if 4%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_005": PathogenInfo(
        pathogen_id="disease_vector_34_005",
        common_name="Pathogen Condition Variant 34-5",
        scientific_name="Pathogen strain 34.5",
        pathogen_type=PathogenType.FUNGAL if 5%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_006": PathogenInfo(
        pathogen_id="disease_vector_34_006",
        common_name="Pathogen Condition Variant 34-6",
        scientific_name="Pathogen strain 34.6",
        pathogen_type=PathogenType.FUNGAL if 6%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_007": PathogenInfo(
        pathogen_id="disease_vector_34_007",
        common_name="Pathogen Condition Variant 34-7",
        scientific_name="Pathogen strain 34.7",
        pathogen_type=PathogenType.FUNGAL if 7%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_008": PathogenInfo(
        pathogen_id="disease_vector_34_008",
        common_name="Pathogen Condition Variant 34-8",
        scientific_name="Pathogen strain 34.8",
        pathogen_type=PathogenType.FUNGAL if 8%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_009": PathogenInfo(
        pathogen_id="disease_vector_34_009",
        common_name="Pathogen Condition Variant 34-9",
        scientific_name="Pathogen strain 34.9",
        pathogen_type=PathogenType.FUNGAL if 9%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_010": PathogenInfo(
        pathogen_id="disease_vector_34_010",
        common_name="Pathogen Condition Variant 34-10",
        scientific_name="Pathogen strain 34.10",
        pathogen_type=PathogenType.FUNGAL if 10%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_011": PathogenInfo(
        pathogen_id="disease_vector_34_011",
        common_name="Pathogen Condition Variant 34-11",
        scientific_name="Pathogen strain 34.11",
        pathogen_type=PathogenType.FUNGAL if 11%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_012": PathogenInfo(
        pathogen_id="disease_vector_34_012",
        common_name="Pathogen Condition Variant 34-12",
        scientific_name="Pathogen strain 34.12",
        pathogen_type=PathogenType.FUNGAL if 12%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_013": PathogenInfo(
        pathogen_id="disease_vector_34_013",
        common_name="Pathogen Condition Variant 34-13",
        scientific_name="Pathogen strain 34.13",
        pathogen_type=PathogenType.FUNGAL if 13%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_014": PathogenInfo(
        pathogen_id="disease_vector_34_014",
        common_name="Pathogen Condition Variant 34-14",
        scientific_name="Pathogen strain 34.14",
        pathogen_type=PathogenType.FUNGAL if 14%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_015": PathogenInfo(
        pathogen_id="disease_vector_34_015",
        common_name="Pathogen Condition Variant 34-15",
        scientific_name="Pathogen strain 34.15",
        pathogen_type=PathogenType.FUNGAL if 15%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_016": PathogenInfo(
        pathogen_id="disease_vector_34_016",
        common_name="Pathogen Condition Variant 34-16",
        scientific_name="Pathogen strain 34.16",
        pathogen_type=PathogenType.FUNGAL if 16%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_017": PathogenInfo(
        pathogen_id="disease_vector_34_017",
        common_name="Pathogen Condition Variant 34-17",
        scientific_name="Pathogen strain 34.17",
        pathogen_type=PathogenType.FUNGAL if 17%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_018": PathogenInfo(
        pathogen_id="disease_vector_34_018",
        common_name="Pathogen Condition Variant 34-18",
        scientific_name="Pathogen strain 34.18",
        pathogen_type=PathogenType.FUNGAL if 18%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_019": PathogenInfo(
        pathogen_id="disease_vector_34_019",
        common_name="Pathogen Condition Variant 34-19",
        scientific_name="Pathogen strain 34.19",
        pathogen_type=PathogenType.FUNGAL if 19%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_020": PathogenInfo(
        pathogen_id="disease_vector_34_020",
        common_name="Pathogen Condition Variant 34-20",
        scientific_name="Pathogen strain 34.20",
        pathogen_type=PathogenType.FUNGAL if 20%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_021": PathogenInfo(
        pathogen_id="disease_vector_34_021",
        common_name="Pathogen Condition Variant 34-21",
        scientific_name="Pathogen strain 34.21",
        pathogen_type=PathogenType.FUNGAL if 21%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_022": PathogenInfo(
        pathogen_id="disease_vector_34_022",
        common_name="Pathogen Condition Variant 34-22",
        scientific_name="Pathogen strain 34.22",
        pathogen_type=PathogenType.FUNGAL if 22%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_023": PathogenInfo(
        pathogen_id="disease_vector_34_023",
        common_name="Pathogen Condition Variant 34-23",
        scientific_name="Pathogen strain 34.23",
        pathogen_type=PathogenType.FUNGAL if 23%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_34_024": PathogenInfo(
        pathogen_id="disease_vector_34_024",
        common_name="Pathogen Condition Variant 34-24",
        scientific_name="Pathogen strain 34.24",
        pathogen_type=PathogenType.FUNGAL if 24%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
}
