from agrimind.core.base_models import PathogenInfo
from agrimind.core.domain_types import PathogenType

EXPANDED_DISEASE_DATA_PART_31 = {
    "disease_vector_31_001": PathogenInfo(
        pathogen_id="disease_vector_31_001",
        common_name="Pathogen Condition Variant 31-1",
        scientific_name="Pathogen strain 31.1",
        pathogen_type=PathogenType.FUNGAL if 1%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_002": PathogenInfo(
        pathogen_id="disease_vector_31_002",
        common_name="Pathogen Condition Variant 31-2",
        scientific_name="Pathogen strain 31.2",
        pathogen_type=PathogenType.FUNGAL if 2%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_003": PathogenInfo(
        pathogen_id="disease_vector_31_003",
        common_name="Pathogen Condition Variant 31-3",
        scientific_name="Pathogen strain 31.3",
        pathogen_type=PathogenType.FUNGAL if 3%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_004": PathogenInfo(
        pathogen_id="disease_vector_31_004",
        common_name="Pathogen Condition Variant 31-4",
        scientific_name="Pathogen strain 31.4",
        pathogen_type=PathogenType.FUNGAL if 4%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_005": PathogenInfo(
        pathogen_id="disease_vector_31_005",
        common_name="Pathogen Condition Variant 31-5",
        scientific_name="Pathogen strain 31.5",
        pathogen_type=PathogenType.FUNGAL if 5%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_006": PathogenInfo(
        pathogen_id="disease_vector_31_006",
        common_name="Pathogen Condition Variant 31-6",
        scientific_name="Pathogen strain 31.6",
        pathogen_type=PathogenType.FUNGAL if 6%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_007": PathogenInfo(
        pathogen_id="disease_vector_31_007",
        common_name="Pathogen Condition Variant 31-7",
        scientific_name="Pathogen strain 31.7",
        pathogen_type=PathogenType.FUNGAL if 7%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_008": PathogenInfo(
        pathogen_id="disease_vector_31_008",
        common_name="Pathogen Condition Variant 31-8",
        scientific_name="Pathogen strain 31.8",
        pathogen_type=PathogenType.FUNGAL if 8%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_009": PathogenInfo(
        pathogen_id="disease_vector_31_009",
        common_name="Pathogen Condition Variant 31-9",
        scientific_name="Pathogen strain 31.9",
        pathogen_type=PathogenType.FUNGAL if 9%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_010": PathogenInfo(
        pathogen_id="disease_vector_31_010",
        common_name="Pathogen Condition Variant 31-10",
        scientific_name="Pathogen strain 31.10",
        pathogen_type=PathogenType.FUNGAL if 10%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_011": PathogenInfo(
        pathogen_id="disease_vector_31_011",
        common_name="Pathogen Condition Variant 31-11",
        scientific_name="Pathogen strain 31.11",
        pathogen_type=PathogenType.FUNGAL if 11%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_012": PathogenInfo(
        pathogen_id="disease_vector_31_012",
        common_name="Pathogen Condition Variant 31-12",
        scientific_name="Pathogen strain 31.12",
        pathogen_type=PathogenType.FUNGAL if 12%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_013": PathogenInfo(
        pathogen_id="disease_vector_31_013",
        common_name="Pathogen Condition Variant 31-13",
        scientific_name="Pathogen strain 31.13",
        pathogen_type=PathogenType.FUNGAL if 13%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_014": PathogenInfo(
        pathogen_id="disease_vector_31_014",
        common_name="Pathogen Condition Variant 31-14",
        scientific_name="Pathogen strain 31.14",
        pathogen_type=PathogenType.FUNGAL if 14%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_015": PathogenInfo(
        pathogen_id="disease_vector_31_015",
        common_name="Pathogen Condition Variant 31-15",
        scientific_name="Pathogen strain 31.15",
        pathogen_type=PathogenType.FUNGAL if 15%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_016": PathogenInfo(
        pathogen_id="disease_vector_31_016",
        common_name="Pathogen Condition Variant 31-16",
        scientific_name="Pathogen strain 31.16",
        pathogen_type=PathogenType.FUNGAL if 16%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_017": PathogenInfo(
        pathogen_id="disease_vector_31_017",
        common_name="Pathogen Condition Variant 31-17",
        scientific_name="Pathogen strain 31.17",
        pathogen_type=PathogenType.FUNGAL if 17%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_018": PathogenInfo(
        pathogen_id="disease_vector_31_018",
        common_name="Pathogen Condition Variant 31-18",
        scientific_name="Pathogen strain 31.18",
        pathogen_type=PathogenType.FUNGAL if 18%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_019": PathogenInfo(
        pathogen_id="disease_vector_31_019",
        common_name="Pathogen Condition Variant 31-19",
        scientific_name="Pathogen strain 31.19",
        pathogen_type=PathogenType.FUNGAL if 19%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_020": PathogenInfo(
        pathogen_id="disease_vector_31_020",
        common_name="Pathogen Condition Variant 31-20",
        scientific_name="Pathogen strain 31.20",
        pathogen_type=PathogenType.FUNGAL if 20%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_021": PathogenInfo(
        pathogen_id="disease_vector_31_021",
        common_name="Pathogen Condition Variant 31-21",
        scientific_name="Pathogen strain 31.21",
        pathogen_type=PathogenType.FUNGAL if 21%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_022": PathogenInfo(
        pathogen_id="disease_vector_31_022",
        common_name="Pathogen Condition Variant 31-22",
        scientific_name="Pathogen strain 31.22",
        pathogen_type=PathogenType.FUNGAL if 22%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_023": PathogenInfo(
        pathogen_id="disease_vector_31_023",
        common_name="Pathogen Condition Variant 31-23",
        scientific_name="Pathogen strain 31.23",
        pathogen_type=PathogenType.FUNGAL if 23%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_31_024": PathogenInfo(
        pathogen_id="disease_vector_31_024",
        common_name="Pathogen Condition Variant 31-24",
        scientific_name="Pathogen strain 31.24",
        pathogen_type=PathogenType.FUNGAL if 24%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
}
