from agrimind.core.base_models import PathogenInfo
from agrimind.core.domain_types import PathogenType

EXPANDED_DISEASE_DATA_PART_7 = {
    "disease_vector_07_001": PathogenInfo(
        pathogen_id="disease_vector_07_001",
        common_name="Pathogen Condition Variant 7-1",
        scientific_name="Pathogen strain 7.1",
        pathogen_type=PathogenType.FUNGAL if 1%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_002": PathogenInfo(
        pathogen_id="disease_vector_07_002",
        common_name="Pathogen Condition Variant 7-2",
        scientific_name="Pathogen strain 7.2",
        pathogen_type=PathogenType.FUNGAL if 2%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_003": PathogenInfo(
        pathogen_id="disease_vector_07_003",
        common_name="Pathogen Condition Variant 7-3",
        scientific_name="Pathogen strain 7.3",
        pathogen_type=PathogenType.FUNGAL if 3%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_004": PathogenInfo(
        pathogen_id="disease_vector_07_004",
        common_name="Pathogen Condition Variant 7-4",
        scientific_name="Pathogen strain 7.4",
        pathogen_type=PathogenType.FUNGAL if 4%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_005": PathogenInfo(
        pathogen_id="disease_vector_07_005",
        common_name="Pathogen Condition Variant 7-5",
        scientific_name="Pathogen strain 7.5",
        pathogen_type=PathogenType.FUNGAL if 5%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_006": PathogenInfo(
        pathogen_id="disease_vector_07_006",
        common_name="Pathogen Condition Variant 7-6",
        scientific_name="Pathogen strain 7.6",
        pathogen_type=PathogenType.FUNGAL if 6%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_007": PathogenInfo(
        pathogen_id="disease_vector_07_007",
        common_name="Pathogen Condition Variant 7-7",
        scientific_name="Pathogen strain 7.7",
        pathogen_type=PathogenType.FUNGAL if 7%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_008": PathogenInfo(
        pathogen_id="disease_vector_07_008",
        common_name="Pathogen Condition Variant 7-8",
        scientific_name="Pathogen strain 7.8",
        pathogen_type=PathogenType.FUNGAL if 8%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_009": PathogenInfo(
        pathogen_id="disease_vector_07_009",
        common_name="Pathogen Condition Variant 7-9",
        scientific_name="Pathogen strain 7.9",
        pathogen_type=PathogenType.FUNGAL if 9%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_010": PathogenInfo(
        pathogen_id="disease_vector_07_010",
        common_name="Pathogen Condition Variant 7-10",
        scientific_name="Pathogen strain 7.10",
        pathogen_type=PathogenType.FUNGAL if 10%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_011": PathogenInfo(
        pathogen_id="disease_vector_07_011",
        common_name="Pathogen Condition Variant 7-11",
        scientific_name="Pathogen strain 7.11",
        pathogen_type=PathogenType.FUNGAL if 11%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_012": PathogenInfo(
        pathogen_id="disease_vector_07_012",
        common_name="Pathogen Condition Variant 7-12",
        scientific_name="Pathogen strain 7.12",
        pathogen_type=PathogenType.FUNGAL if 12%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_013": PathogenInfo(
        pathogen_id="disease_vector_07_013",
        common_name="Pathogen Condition Variant 7-13",
        scientific_name="Pathogen strain 7.13",
        pathogen_type=PathogenType.FUNGAL if 13%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_014": PathogenInfo(
        pathogen_id="disease_vector_07_014",
        common_name="Pathogen Condition Variant 7-14",
        scientific_name="Pathogen strain 7.14",
        pathogen_type=PathogenType.FUNGAL if 14%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_015": PathogenInfo(
        pathogen_id="disease_vector_07_015",
        common_name="Pathogen Condition Variant 7-15",
        scientific_name="Pathogen strain 7.15",
        pathogen_type=PathogenType.FUNGAL if 15%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_016": PathogenInfo(
        pathogen_id="disease_vector_07_016",
        common_name="Pathogen Condition Variant 7-16",
        scientific_name="Pathogen strain 7.16",
        pathogen_type=PathogenType.FUNGAL if 16%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_017": PathogenInfo(
        pathogen_id="disease_vector_07_017",
        common_name="Pathogen Condition Variant 7-17",
        scientific_name="Pathogen strain 7.17",
        pathogen_type=PathogenType.FUNGAL if 17%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_018": PathogenInfo(
        pathogen_id="disease_vector_07_018",
        common_name="Pathogen Condition Variant 7-18",
        scientific_name="Pathogen strain 7.18",
        pathogen_type=PathogenType.FUNGAL if 18%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_019": PathogenInfo(
        pathogen_id="disease_vector_07_019",
        common_name="Pathogen Condition Variant 7-19",
        scientific_name="Pathogen strain 7.19",
        pathogen_type=PathogenType.FUNGAL if 19%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_020": PathogenInfo(
        pathogen_id="disease_vector_07_020",
        common_name="Pathogen Condition Variant 7-20",
        scientific_name="Pathogen strain 7.20",
        pathogen_type=PathogenType.FUNGAL if 20%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_021": PathogenInfo(
        pathogen_id="disease_vector_07_021",
        common_name="Pathogen Condition Variant 7-21",
        scientific_name="Pathogen strain 7.21",
        pathogen_type=PathogenType.FUNGAL if 21%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_022": PathogenInfo(
        pathogen_id="disease_vector_07_022",
        common_name="Pathogen Condition Variant 7-22",
        scientific_name="Pathogen strain 7.22",
        pathogen_type=PathogenType.FUNGAL if 22%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_023": PathogenInfo(
        pathogen_id="disease_vector_07_023",
        common_name="Pathogen Condition Variant 7-23",
        scientific_name="Pathogen strain 7.23",
        pathogen_type=PathogenType.FUNGAL if 23%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_07_024": PathogenInfo(
        pathogen_id="disease_vector_07_024",
        common_name="Pathogen Condition Variant 7-24",
        scientific_name="Pathogen strain 7.24",
        pathogen_type=PathogenType.FUNGAL if 24%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
}
