from agrimind.core.base_models import PathogenInfo
from agrimind.core.domain_types import PathogenType

EXPANDED_DISEASE_DATA_PART_25 = {
    "disease_vector_25_001": PathogenInfo(
        pathogen_id="disease_vector_25_001",
        common_name="Pathogen Condition Variant 25-1",
        scientific_name="Pathogen strain 25.1",
        pathogen_type=PathogenType.FUNGAL if 1%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_002": PathogenInfo(
        pathogen_id="disease_vector_25_002",
        common_name="Pathogen Condition Variant 25-2",
        scientific_name="Pathogen strain 25.2",
        pathogen_type=PathogenType.FUNGAL if 2%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_003": PathogenInfo(
        pathogen_id="disease_vector_25_003",
        common_name="Pathogen Condition Variant 25-3",
        scientific_name="Pathogen strain 25.3",
        pathogen_type=PathogenType.FUNGAL if 3%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_004": PathogenInfo(
        pathogen_id="disease_vector_25_004",
        common_name="Pathogen Condition Variant 25-4",
        scientific_name="Pathogen strain 25.4",
        pathogen_type=PathogenType.FUNGAL if 4%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_005": PathogenInfo(
        pathogen_id="disease_vector_25_005",
        common_name="Pathogen Condition Variant 25-5",
        scientific_name="Pathogen strain 25.5",
        pathogen_type=PathogenType.FUNGAL if 5%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_006": PathogenInfo(
        pathogen_id="disease_vector_25_006",
        common_name="Pathogen Condition Variant 25-6",
        scientific_name="Pathogen strain 25.6",
        pathogen_type=PathogenType.FUNGAL if 6%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_007": PathogenInfo(
        pathogen_id="disease_vector_25_007",
        common_name="Pathogen Condition Variant 25-7",
        scientific_name="Pathogen strain 25.7",
        pathogen_type=PathogenType.FUNGAL if 7%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_008": PathogenInfo(
        pathogen_id="disease_vector_25_008",
        common_name="Pathogen Condition Variant 25-8",
        scientific_name="Pathogen strain 25.8",
        pathogen_type=PathogenType.FUNGAL if 8%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_009": PathogenInfo(
        pathogen_id="disease_vector_25_009",
        common_name="Pathogen Condition Variant 25-9",
        scientific_name="Pathogen strain 25.9",
        pathogen_type=PathogenType.FUNGAL if 9%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_010": PathogenInfo(
        pathogen_id="disease_vector_25_010",
        common_name="Pathogen Condition Variant 25-10",
        scientific_name="Pathogen strain 25.10",
        pathogen_type=PathogenType.FUNGAL if 10%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_011": PathogenInfo(
        pathogen_id="disease_vector_25_011",
        common_name="Pathogen Condition Variant 25-11",
        scientific_name="Pathogen strain 25.11",
        pathogen_type=PathogenType.FUNGAL if 11%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_012": PathogenInfo(
        pathogen_id="disease_vector_25_012",
        common_name="Pathogen Condition Variant 25-12",
        scientific_name="Pathogen strain 25.12",
        pathogen_type=PathogenType.FUNGAL if 12%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_013": PathogenInfo(
        pathogen_id="disease_vector_25_013",
        common_name="Pathogen Condition Variant 25-13",
        scientific_name="Pathogen strain 25.13",
        pathogen_type=PathogenType.FUNGAL if 13%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_014": PathogenInfo(
        pathogen_id="disease_vector_25_014",
        common_name="Pathogen Condition Variant 25-14",
        scientific_name="Pathogen strain 25.14",
        pathogen_type=PathogenType.FUNGAL if 14%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_015": PathogenInfo(
        pathogen_id="disease_vector_25_015",
        common_name="Pathogen Condition Variant 25-15",
        scientific_name="Pathogen strain 25.15",
        pathogen_type=PathogenType.FUNGAL if 15%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_016": PathogenInfo(
        pathogen_id="disease_vector_25_016",
        common_name="Pathogen Condition Variant 25-16",
        scientific_name="Pathogen strain 25.16",
        pathogen_type=PathogenType.FUNGAL if 16%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_017": PathogenInfo(
        pathogen_id="disease_vector_25_017",
        common_name="Pathogen Condition Variant 25-17",
        scientific_name="Pathogen strain 25.17",
        pathogen_type=PathogenType.FUNGAL if 17%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_018": PathogenInfo(
        pathogen_id="disease_vector_25_018",
        common_name="Pathogen Condition Variant 25-18",
        scientific_name="Pathogen strain 25.18",
        pathogen_type=PathogenType.FUNGAL if 18%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_019": PathogenInfo(
        pathogen_id="disease_vector_25_019",
        common_name="Pathogen Condition Variant 25-19",
        scientific_name="Pathogen strain 25.19",
        pathogen_type=PathogenType.FUNGAL if 19%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_020": PathogenInfo(
        pathogen_id="disease_vector_25_020",
        common_name="Pathogen Condition Variant 25-20",
        scientific_name="Pathogen strain 25.20",
        pathogen_type=PathogenType.FUNGAL if 20%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_021": PathogenInfo(
        pathogen_id="disease_vector_25_021",
        common_name="Pathogen Condition Variant 25-21",
        scientific_name="Pathogen strain 25.21",
        pathogen_type=PathogenType.FUNGAL if 21%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_022": PathogenInfo(
        pathogen_id="disease_vector_25_022",
        common_name="Pathogen Condition Variant 25-22",
        scientific_name="Pathogen strain 25.22",
        pathogen_type=PathogenType.FUNGAL if 22%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_023": PathogenInfo(
        pathogen_id="disease_vector_25_023",
        common_name="Pathogen Condition Variant 25-23",
        scientific_name="Pathogen strain 25.23",
        pathogen_type=PathogenType.FUNGAL if 23%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
    "disease_vector_25_024": PathogenInfo(
        pathogen_id="disease_vector_25_024",
        common_name="Pathogen Condition Variant 25-24",
        scientific_name="Pathogen strain 25.24",
        pathogen_type=PathogenType.FUNGAL if 24%2==0 else PathogenType.BACTERIAL,
        host_crops=["wheat_bread", "rice_indica", "maize_field", "tomato_hybrid"],
        symptoms=["foliar_chlorosis", "water_soaked_lesions", "necrotic_spots"],
        favorable_humidity_min=75.0,
        favorable_temp_min=15.0,
        favorable_temp_max=28.0,
        chemical_treatment=["Mancozeb 75% WP", "Propiconazole 25% EC"],
        organic_treatment=["Neem oil spray", "Trichoderma viride"],
        preventative_measures=["Crop rotation", "Seed treatment", "Field sanitation"]
    ),
}
